# Generated by Django 3.1.5 on 2021-02-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='persons/tmp.jpg', upload_to='persons'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='persons/tmp.jpg', upload_to='persons'),
        ),
    ]
